changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: ⚡ المميزات الجديدة
      labels:
        - feature
        - enhancement
    - title: 🐛 إصلاحات
      labels:
        - bug
        - fix
    - title: 📚 التوثيق
      labels:
        - documentation
    - title: ⚙️ تحسينات تقنية
      labels:
        - technical
        - refactor
