name: flutter_publisher
description: تطبيق سطح مكتب احترافي لبناء ونشر وإدارة تطبيقات Flutter بشكل تلقائي
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    # دعم التعريب واللغات:
    # - ترجمة النصوص
    # - تنسيق التواريخ
    # - دعم RTL/LTR

  #======================================
  # 1. واجهة المستخدم
  #======================================
  fluent_ui: ^4.9.2
    # واجهة مستخدم Windows:
    # - مكونات جاهزة بنمط Windows
    # - تناسق التصميم مع النظام
    # - أزرار وقوائم احترافية
    # - دعم للإيماءات واللمس

  window_manager: ^0.3.9
    # إدارة نافذة التطبيق:
    # - تغيير حجم النافذة
    # - تحريك النافذة بسلاسة
    # - التحكم في شريط العنوان
    # - الحد الأدنى/الأقصى للنافذة

  system_theme: ^2.3.1
    # تكامل مع سمة النظام
    # - وضع داكن/فاتح تلقائي
    # - ألوان النظام
    # - دعم Fluent UI

  flutter_screenutil: ^5.9.0
    # التكيف مع أحجام الشاشات
    # - تناسق العناصر
    # - دعم جميع الأجهزة

  easy_splash_screen: ^1.0.4
    # شاشة البداية
    # - سهلة التخصيص
    # - دعم الصور والحركات
    # - تحميل الموارد في الخلفية

  google_fonts: ^6.1.0
    # مكتبة Google Fonts:
    # - أكثر من 1000 خط مجاني
    # - دعم للخطوط العربية
    # - تحميل تلقائي للخطوط
    # - أداء عالي

  #======================================
  # 2. إدارة الحالة والبيانات
  #======================================
  get: ^4.6.6
    # إدارة الحالة والتنقل:
    # - إدارة حالة التطبيق بشكل فعال
    # - التنقل بين الشاشات بسهولة
    # - حقن التبعيات بشكل مرن
    # - إدارة الموارد والذاكرة

  get_storage: ^2.1.1
    # تخزين محلي
    # - حفظ الإعدادات
    # - تخزين مؤقت

  #======================================
  # 3. قاعدة البيانات والخدمات
  #======================================
  firedart: ^0.9.7
    # Firebase للتطبيقات المكتبية
    # - المصادقة
    # - قاعدة بيانات Firestore
    # - متوافق مع Windows/Linux/macOS

  #======================================
  # 4. التكامل والعمليات
  #======================================
  github: ^9.22.0
    # تكامل GitHub
    # - إدارة المستودعات
    # - نشر الإصدارات

  dio: ^5.4.0
    # طلبات HTTP
    # - تحميل الملفات
    # - معالجة الأخطاء

  #======================================
  # 5. التحديث والتوزيع
  #======================================
  upgrader: ^8.3.0
    # تحديث تلقائي
    # - فحص التحديثات
    # - تنزيل وتثبيت
    # - تحديثات إجبارية

  flutter_distributor: ^0.0.2
    # توزيع التطبيق
    # - بناء حزم التثبيت
    # - دعم المنصات المختلفة

  #======================================
  # 6. عرض البيانات
  #======================================
  data_table_2: ^2.5.9
    # جداول البيانات
    # - عرض منظم
    # - فرز وتصفية

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
    # تحليل الكود

  build_runner: ^2.4.8
    # توليد الكود:
    # - توليد نماذج JSON
    # - إنشاء الترجمات
    # - نماذج Serverpod
    # - توليد المصادر
    # - معالجة التعليقات
    # - تحسين الأداء

  flutter_gen_runner: ^5.3.2
    # توليد كود للـ assets:
    # - وصول آمن للملفات
    # - اكتشاف الأخطاء وقت البناء
    # - دعم SVG كـ widgets
    # - توليد ثوابت للألوان والخطوط
    # - تكامل مع IDE
    # - تحسين الأداء

flutter:
  uses-material-design: true
  
  generate: true  # تفعيل توليد الكود

  assets:
    # الصور والرسومات
    - assets/images/
      # - صور الواجهة
      # - الشعارات
      # - الصور التوضيحية
      # - الخلفيات
    
    # الأيقونات والرموز
    - assets/icons/
      # - أيقونات التطبيق
      # - أيقونات القوائم
      # - الرموز التفاعلية
      # - SVG icons
    
    # ملفات الإعدادات
    - assets/config/
      # - إعدادات التطبيق
      # - ملفات JSON
      # - ملفات YAML
      # - متغيرات البيئة
    
    # البيانات الثابتة
    - assets/data/
      # - بيانات القوائم
      # - النصوص الثابتة
      # - بيانات التهيئة
      # - نماذج البيانات
    
    # الرسوم المتحركة
    - assets/animations/
      # - ملفات Lottie
      # - GIF المتحركة
      # - تأثيرات الحركة
    
    # الأصوات
    - assets/audio/
      # - التنبيهات
      # - المؤثرات الصوتية
      # - الموسيقى الخلفية

 # تعطيل توليد الكود للخطوط لأننا نستخدم Google Fonts

# إعدادات توليد الكود للـ assets
flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true
    
  colors:
    enabled: true
    inputs:
      - assets/config/colors.xml
